version: "3"
services:
  www:
    image: nginx:1.22.0-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: mongo:5.0.11-focal
    environment:
    - PUID=1000
    - PGID=1000
    ports:
    - 27017:27017
  php:
    image: php:8.1-fpm-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  composer:
      image: composer:2.4.1
      working_dir: /var/www/html
      command: install
      volumes: 
        - ./:/var/www/html